import type { AppConfig } from './app-config.model';

// Minimal Storage subset the loader needs — lets tests inject a fake without depending on
// jsdom's localStorage, and lets the default resolve to `undefined` (rather than throwing) in
// environments where `localStorage` itself is unavailable (e.g. some sandboxed/private contexts).
export interface AppConfigStorage {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

export const APP_CONFIG_STORAGE_KEY = 'birrapoint.appConfig';

function defaultStorage(): AppConfigStorage | null {
  try {
    return globalThis.localStorage ?? null;
  } catch {
    return null;
  }
}

// Best-effort read of the last-known-good config (R-08 offline fallback). Any failure — no
// storage, nothing cached yet, corrupted JSON, a cached payload that no longer validates — is
// treated as "no fallback available", never as a hard error; the caller decides what to do next.
function readCachedConfig(storage: AppConfigStorage | null): AppConfig | null {
  if (!storage) {
    return null;
  }
  try {
    const raw = storage.getItem(APP_CONFIG_STORAGE_KEY);
    if (!raw) {
      return null;
    }
    return validate(JSON.parse(raw));
  } catch {
    return null;
  }
}

// Best-effort write. Storage can be unavailable or full (private browsing, quota) — that must
// never fail the load of a config that was just successfully fetched and validated.
function writeCachedConfig(storage: AppConfigStorage | null, config: AppConfig): void {
  if (!storage) {
    return;
  }
  try {
    storage.setItem(APP_CONFIG_STORAGE_KEY, JSON.stringify(config));
  } catch {
    // Ignored — see comment above.
  }
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

function stripTrailingSlash(value: string): string {
  return value.endsWith('/') ? value.slice(0, -1) : value;
}

function validate(raw: unknown): AppConfig {
  const candidate = raw as Partial<AppConfig> | null | undefined;
  const keycloak = candidate?.keycloak;

  if (
    !candidate ||
    !keycloak ||
    !isNonEmptyString(keycloak.url) ||
    !isNonEmptyString(keycloak.realm) ||
    !isNonEmptyString(keycloak.clientId) ||
    typeof candidate.apiBaseUrl !== 'string'
  ) {
    throw new Error(
      'Invalid runtime configuration in /config.json: expected ' +
        '{ keycloak: { url, realm, clientId }, apiBaseUrl }.',
    );
  }

  return {
    keycloak: {
      url: stripTrailingSlash(keycloak.url),
      realm: keycloak.realm,
      clientId: keycloak.clientId,
    },
    apiBaseUrl: stripTrailingSlash(candidate.apiBaseUrl),
  };
}

/**
 * Fetches and validates the runtime config (FR-043) before Angular bootstraps (main.ts). Locally
 * and in ng serve, frontend/public/config.json is served as-is; in production it's generated by
 * the nginx entrypoint from env vars at container start — never build-time-inlined.
 *
 * `cache: 'no-cache'` forces a conditional revalidation on every load instead of an implicit
 * browser HTTP cache hit, so a container redeploy with new env vars takes effect on next load
 * (this is separate from — and layered under — the service worker's own dataGroups freshness
 * strategy for /config.json, which covers the fully-offline case).
 *
 * Last-known-good fallback (R-08): if the request itself fails (offline) or comes back non-OK, a
 * previously validated config persisted to `storage` is used instead — otherwise a judge opening
 * the installed PWA offline the next day would hit the fatal error screen just because the first
 * network hop for /config.json didn't complete before the service worker could serve its own
 * cached copy. A 200 response that fails validation is a real server misconfiguration, not an
 * offline scenario, and always throws — it never falls back to a stale cache.
 */
export async function loadAppConfig(
  fetchFn: typeof fetch = fetch,
  storage: AppConfigStorage | null = defaultStorage(),
): Promise<AppConfig> {
  let response: Response;
  try {
    response = await fetchFn('/config.json', { cache: 'no-cache' });
  } catch (error) {
    const cached = readCachedConfig(storage);
    if (cached) {
      return cached;
    }
    throw error;
  }

  if (!response.ok) {
    const cached = readCachedConfig(storage);
    if (cached) {
      return cached;
    }
    throw new Error(
      `Failed to load runtime configuration from /config.json: HTTP ${response.status}`,
    );
  }

  const raw: unknown = await response.json();
  const config = validate(raw);
  writeCachedConfig(storage, config);
  return config;
}
