import type { AppConfig } from './app-config.model';

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

function stripTrailingSlash(value: string): string {
  return value.endsWith('/') ? value.slice(0, -1) : value;
}

function validate(raw: unknown): AppConfig {
  const candidate = raw as Partial<AppConfig> | null | undefined;
  const keycloak = candidate?.keycloak;

  if (
    !candidate ||
    !keycloak ||
    !isNonEmptyString(keycloak.url) ||
    !isNonEmptyString(keycloak.realm) ||
    !isNonEmptyString(keycloak.clientId) ||
    typeof candidate.apiBaseUrl !== 'string'
  ) {
    throw new Error(
      'Invalid runtime configuration in /config.json: expected ' +
        '{ keycloak: { url, realm, clientId }, apiBaseUrl }.',
    );
  }

  return {
    keycloak: {
      url: stripTrailingSlash(keycloak.url),
      realm: keycloak.realm,
      clientId: keycloak.clientId,
    },
    apiBaseUrl: stripTrailingSlash(candidate.apiBaseUrl),
  };
}

/**
 * Fetches and validates the runtime config (FR-043) before Angular bootstraps (main.ts). Locally
 * and in ng serve, frontend/public/config.json is served as-is; in production it's generated by
 * the nginx entrypoint from env vars at container start — never build-time-inlined.
 *
 * `cache: 'no-cache'` forces a conditional revalidation on every load instead of an implicit
 * browser HTTP cache hit, so a container redeploy with new env vars takes effect on next load
 * (this is separate from — and layered under — the service worker's own dataGroups freshness
 * strategy for /config.json, which covers the fully-offline case).
 */
export async function loadAppConfig(fetchFn: typeof fetch = fetch): Promise<AppConfig> {
  const response = await fetchFn('/config.json', { cache: 'no-cache' });

  if (!response.ok) {
    throw new Error(
      `Failed to load runtime configuration from /config.json: HTTP ${response.status}`,
    );
  }

  const raw: unknown = await response.json();
  return validate(raw);
}
